# This is a basic workflow to help you get started with Actions

name: openvino-CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the refactor branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: build ros2 openvino toolkit
      uses: docker://congliu0913/ros2:ros2_openvino
      with:
        args: bash /github/workspace/.github/ciscript/ci_build_ros2_openvino_toolkit.sh

    # Runs a set of commands using the runners shell
    - name: test ros2 openvino toolkit
      uses: docker://congliu0913/ros2:ros2_openvino
      with:
        args: bash /github/workspace/.github/ciscript/ci_test_ros2_openvino_toolkit.sh
