name: refactor-CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the refactor branch
on:
  push:
    branches: [ CI-dev-ov.2020.3 ]
  pull_request:
    branches: [ CI-dev-ov.2020.3 ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # install ros2 foxy
    - uses: ros-tooling/setup-ros@0.1.1
      with:
        required-ros-distributions: foxy
    - run: "source /opt/ros/foxy/setup.bash && ros2 run --help"
