name: refactor-CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the refactor branch
on:
  push:
    branches: [ CI-dev-ov.2020.3 ]
  pull_request:
    branches: [ CI-dev-ov.2020.3 ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # install ros2 eloquent
    - uses: ros-tooling/setup-ros@0.1.1
      with:
        required-ros-distributions: eloquent
    - run: "source /opt/ros/eloquent/setup.bash && ros2 run --help"
    
    # install openvino 2020.3
    - name: install openvino 2020.3
      run: |
        sudo apt update && sudo apt install curl gnupg2 lsb-release
        curl -s https://apt.repos.intel.com/openvino/2020/GPG-PUB-KEY-INTEL-OPENVINO-2020 |sudo apt-key add -
        echo "deb https://apt.repos.intel.com/openvino/2020 all main" | sudo tee /etc/apt/sources.list.d/intel-openvino-2020.list
        sudo apt update
        sudo apt-cache search openvino
        sudo apt-get install -y intel-openvino-runtime-ubuntu18-2020.3.194 intel-openvino-ie-samples-2020.3.194 intel-openvino-omz-dev-2020.3.194 intel-openvino-omz-tools-2020.3.341
        ls -lh /opt/intel/openvino
        source /opt/intel/openvino/bin/setupvars.sh
